/*
 _  _  _              _           
(_)| || | _   _  ___ | | __ _   _ 
| || || || | | |/ __|| |/ /| | | |
| || || || |_| |\__ \|   < | |_| |
|_||_||_| \__, ||___/|_|\_\ \__, |
          |___/             |___/

Driver for Memsic mxc6655xa v1.0.0
Copyright © 2024 illysky
*/   

#ifndef __mxc6655xa_H
#define __mxc6655xa_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/kernel.h>

// MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_ADDR 0x00
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SIZE 1
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SHXP_GET(v) FIELD_GET(GENMASK(0,0),v)
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SHXP_SET(i, v) (((i) & ~(GENMASK(0,0))) | FIELD_PREP((GENMASK(0,0)),(v)))
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SHXM_GET(v) FIELD_GET(GENMASK(1,1),v)
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SHXM_SET(i, v) (((i) & ~(GENMASK(1,1))) | FIELD_PREP((GENMASK(1,1)),(v)))
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SHYP_GET(v) FIELD_GET(GENMASK(2,2),v)
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SHYP_SET(i, v) (((i) & ~(GENMASK(2,2))) | FIELD_PREP((GENMASK(2,2)),(v)))
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SHYM_GET(v) FIELD_GET(GENMASK(3,3),v)
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_SHYM_SET(i, v) (((i) & ~(GENMASK(3,3))) | FIELD_PREP((GENMASK(3,3)),(v)))
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_CHORXY_GET(v) FIELD_GET(GENMASK(6,6),v)
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_CHORXY_SET(i, v) (((i) & ~(GENMASK(6,6))) | FIELD_PREP((GENMASK(6,6)),(v)))
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_CHORZ_GET(v) FIELD_GET(GENMASK(7,7),v)
#define MXC6655XA_SHAKE_CHANGE_ORIENTATION_IRQ_CHORZ_SET(i, v) (((i) & ~(GENMASK(7,7))) | FIELD_PREP((GENMASK(7,7)),(v)))

// MXC6655XA_DATA_READY_IRQ_SRC
#define MXC6655XA_DATA_READY_IRQ_SRC_ADDR 0x01
#define MXC6655XA_DATA_READY_IRQ_SRC_SIZE 1
#define MXC6655XA_DATA_READY_IRQ_SRC_DRDY_GET(v) FIELD_GET(GENMASK(0,0),v)
#define MXC6655XA_DATA_READY_IRQ_SRC_DRDY_SET(i, v) (((i) & ~(GENMASK(0,0))) | FIELD_PREP((GENMASK(0,0)),(v)))
#define MXC6655XA_DATA_READY_IRQ_SRC_ORXY_GET(v) FIELD_GET(GENMASK(5,4),v)
#define MXC6655XA_DATA_READY_IRQ_SRC_ORXY_SET(i, v) (((i) & ~(GENMASK(5,4))) | FIELD_PREP((GENMASK(5,4)),(v)))
#define MXC6655XA_DATA_READY_IRQ_SRC_ORZ_GET(v) FIELD_GET(GENMASK(6,6),v)
#define MXC6655XA_DATA_READY_IRQ_SRC_ORZ_SET(i, v) (((i) & ~(GENMASK(6,6))) | FIELD_PREP((GENMASK(6,6)),(v)))
#define MXC6655XA_DATA_READY_IRQ_SRC_TILT_GET(v) FIELD_GET(GENMASK(7,7),v)
#define MXC6655XA_DATA_READY_IRQ_SRC_TILT_SET(i, v) (((i) & ~(GENMASK(7,7))) | FIELD_PREP((GENMASK(7,7)),(v)))

// MXC6655XA_INST_ORIENTATION_STATUS
#define MXC6655XA_INST_ORIENTATION_STATUS_ADDR 0x02
#define MXC6655XA_INST_ORIENTATION_STATUS_SIZE 1
#define MXC6655XA_INST_ORIENTATION_STATUS_ORIXY_GET(v) FIELD_GET(GENMASK(1,0),v)
#define MXC6655XA_INST_ORIENTATION_STATUS_ORIXY_SET(i, v) (((i) & ~(GENMASK(1,0))) | FIELD_PREP((GENMASK(1,0)),(v)))
#define MXC6655XA_INST_ORIENTATION_STATUS_ORIZ_GET(v) FIELD_GET(GENMASK(3,2),v)
#define MXC6655XA_INST_ORIENTATION_STATUS_ORIZ_SET(i, v) (((i) & ~(GENMASK(3,2))) | FIELD_PREP((GENMASK(3,2)),(v)))
#define MXC6655XA_INST_ORIENTATION_STATUS_ORD_GET(v) FIELD_GET(GENMASK(4,4),v)
#define MXC6655XA_INST_ORIENTATION_STATUS_ORD_SET(i, v) (((i) & ~(GENMASK(4,4))) | FIELD_PREP((GENMASK(4,4)),(v)))

// MXC6655XA_X_AXIS_XL_MSB
#define MXC6655XA_X_AXIS_XL_MSB_ADDR 0x03
#define MXC6655XA_X_AXIS_XL_MSB_SIZE 1
#define MXC6655XA_X_AXIS_XL_MSB_D_GET(v) FIELD_GET(GENMASK(7,0),v)
#define MXC6655XA_X_AXIS_XL_MSB_D_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// MXC6655XA_X_AXIS_XL_LSB
#define MXC6655XA_X_AXIS_XL_LSB_ADDR 0x04
#define MXC6655XA_X_AXIS_XL_LSB_SIZE 1
#define MXC6655XA_X_AXIS_XL_LSB_D_GET(v) FIELD_GET(GENMASK(7,4),v)
#define MXC6655XA_X_AXIS_XL_LSB_D_SET(i, v) (((i) & ~(GENMASK(7,4))) | FIELD_PREP((GENMASK(7,4)),(v)))

// MXC6655XA_Y_AXIS_XL_MSB
#define MXC6655XA_Y_AXIS_XL_MSB_ADDR 0x05
#define MXC6655XA_Y_AXIS_XL_MSB_SIZE 1
#define MXC6655XA_Y_AXIS_XL_MSB_D_GET(v) FIELD_GET(GENMASK(7,0),v)
#define MXC6655XA_Y_AXIS_XL_MSB_D_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// MXC6655XA_Y_AXIS_XL_LSB
#define MXC6655XA_Y_AXIS_XL_LSB_ADDR 0x06
#define MXC6655XA_Y_AXIS_XL_LSB_SIZE 1
#define MXC6655XA_Y_AXIS_XL_LSB_D_GET(v) FIELD_GET(GENMASK(7,4),v)
#define MXC6655XA_Y_AXIS_XL_LSB_D_SET(i, v) (((i) & ~(GENMASK(7,4))) | FIELD_PREP((GENMASK(7,4)),(v)))

// MXC6655XA_Z_AXIS_XL_MSB
#define MXC6655XA_Z_AXIS_XL_MSB_ADDR 0x07
#define MXC6655XA_Z_AXIS_XL_MSB_SIZE 1
#define MXC6655XA_Z_AXIS_XL_MSB_D_GET(v) FIELD_GET(GENMASK(7,0),v)
#define MXC6655XA_Z_AXIS_XL_MSB_D_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// MXC6655XA_Z_AXIS_XL_LSB
#define MXC6655XA_Z_AXIS_XL_LSB_ADDR 0x08
#define MXC6655XA_Z_AXIS_XL_LSB_SIZE 1
#define MXC6655XA_Z_AXIS_XL_LSB_D_GET(v) FIELD_GET(GENMASK(7,4),v)
#define MXC6655XA_Z_AXIS_XL_LSB_D_SET(i, v) (((i) & ~(GENMASK(7,4))) | FIELD_PREP((GENMASK(7,4)),(v)))

// MXC6655XA_TEMPERATURE_OUTPUT
#define MXC6655XA_TEMPERATURE_OUTPUT_ADDR 0x09
#define MXC6655XA_TEMPERATURE_OUTPUT_SIZE 1
#define MXC6655XA_TEMPERATURE_OUTPUT_D_GET(v) FIELD_GET(GENMASK(7,0),v)
#define MXC6655XA_TEMPERATURE_OUTPUT_D_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_ADDR 0x0A
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SIZE 1
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SHXPE_GET(v) FIELD_GET(GENMASK(0,0),v)
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SHXPE_SET(i, v) (((i) & ~(GENMASK(0,0))) | FIELD_PREP((GENMASK(0,0)),(v)))
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SHXME_GET(v) FIELD_GET(GENMASK(1,1),v)
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SHXME_SET(i, v) (((i) & ~(GENMASK(1,1))) | FIELD_PREP((GENMASK(1,1)),(v)))
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SHYPE_GET(v) FIELD_GET(GENMASK(2,2),v)
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SHYPE_SET(i, v) (((i) & ~(GENMASK(2,2))) | FIELD_PREP((GENMASK(2,2)),(v)))
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SHYME_GET(v) FIELD_GET(GENMASK(3,3),v)
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_SHYME_SET(i, v) (((i) & ~(GENMASK(3,3))) | FIELD_PREP((GENMASK(3,3)),(v)))
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_ORXYE_GET(v) FIELD_GET(GENMASK(6,6),v)
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_ORXYE_SET(i, v) (((i) & ~(GENMASK(6,6))) | FIELD_PREP((GENMASK(6,6)),(v)))
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_ORZE_GET(v) FIELD_GET(GENMASK(7,7),v)
#define MXC6655XA_SHAKE_ORIENTATION_IRQ_MASK_ORZE_SET(i, v) (((i) & ~(GENMASK(7,7))) | FIELD_PREP((GENMASK(7,7)),(v)))

// MXC6655XA_DATA_READY_IRQ_MASK
#define MXC6655XA_DATA_READY_IRQ_MASK_ADDR 0x0B
#define MXC6655XA_DATA_READY_IRQ_MASK_SIZE 1
#define MXC6655XA_DATA_READY_IRQ_MASK_DRDYE_GET(v) FIELD_GET(GENMASK(0,0),v)
#define MXC6655XA_DATA_READY_IRQ_MASK_DRDYE_SET(i, v) (((i) & ~(GENMASK(0,0))) | FIELD_PREP((GENMASK(0,0)),(v)))
#define MXC6655XA_DATA_READY_IRQ_MASK_TC_GET(v) FIELD_GET(GENMASK(7,7),v)
#define MXC6655XA_DATA_READY_IRQ_MASK_TC_SET(i, v) (((i) & ~(GENMASK(7,7))) | FIELD_PREP((GENMASK(7,7)),(v)))

// MXC6655XA_ORIENTATION_SHAKE_DET
#define MXC6655XA_ORIENTATION_SHAKE_DET_ADDR 0x0C
#define MXC6655XA_ORIENTATION_SHAKE_DET_SIZE 1
#define MXC6655XA_ORIENTATION_SHAKE_DET_ORC_GET(v) FIELD_GET(GENMASK(1,0),v)
#define MXC6655XA_ORIENTATION_SHAKE_DET_ORC_SET(i, v) (((i) & ~(GENMASK(1,0))) | FIELD_PREP((GENMASK(1,0)),(v)))
#define MXC6655XA_ORIENTATION_SHAKE_DET_SHC_GET(v) FIELD_GET(GENMASK(3,2),v)
#define MXC6655XA_ORIENTATION_SHAKE_DET_SHC_SET(i, v) (((i) & ~(GENMASK(3,2))) | FIELD_PREP((GENMASK(3,2)),(v)))
#define MXC6655XA_ORIENTATION_SHAKE_DET_SHTH_GET(v) FIELD_GET(GENMASK(6,4),v)
#define MXC6655XA_ORIENTATION_SHAKE_DET_SHTH_SET(i, v) (((i) & ~(GENMASK(6,4))) | FIELD_PREP((GENMASK(6,4)),(v)))
#define MXC6655XA_ORIENTATION_SHAKE_DET_SHM_GET(v) FIELD_GET(GENMASK(7,7),v)
#define MXC6655XA_ORIENTATION_SHAKE_DET_SHM_SET(i, v) (((i) & ~(GENMASK(7,7))) | FIELD_PREP((GENMASK(7,7)),(v)))

// MXC6655XA_OPERATING_MODE_CTRL
#define MXC6655XA_OPERATING_MODE_CTRL_ADDR 0x0D
#define MXC6655XA_OPERATING_MODE_CTRL_SIZE 1
#define MXC6655XA_OPERATING_MODE_CTRL_PD_GET(v) FIELD_GET(GENMASK(0,0),v)
#define MXC6655XA_OPERATING_MODE_CTRL_PD_SET(i, v) (((i) & ~(GENMASK(0,0))) | FIELD_PREP((GENMASK(0,0)),(v)))
#define MXC6655XA_OPERATING_MODE_CTRL_FSR_GET(v) FIELD_GET(GENMASK(6,5),v)
#define MXC6655XA_OPERATING_MODE_CTRL_FSR_SET(i, v) (((i) & ~(GENMASK(6,5))) | FIELD_PREP((GENMASK(6,5)),(v)))
#define MXC6655XA_OPERATING_MODE_CTRL_ST_GET(v) FIELD_GET(GENMASK(7,7),v)
#define MXC6655XA_OPERATING_MODE_CTRL_ST_SET(i, v) (((i) & ~(GENMASK(7,7))) | FIELD_PREP((GENMASK(7,7)),(v)))

// MXC6655XA_WHO_AM_I
#define MXC6655XA_WHO_AM_I_ADDR 0x0F
#define MXC6655XA_WHO_AM_I_SIZE 1
#define MXC6655XA_WHO_AM_I_ID_GET(v) FIELD_GET(GENMASK(3,0),v)
#define MXC6655XA_WHO_AM_I_ID_SET(i, v) (((i) & ~(GENMASK(3,0))) | FIELD_PREP((GENMASK(3,0)),(v)))



#ifdef __cplusplus
}
#endif
#endif // mxc6655xa_H