/*
 _  _  _              _           
(_)| || | _   _  ___ | | __ _   _ 
| || || || | | |/ __|| |/ /| | | |
| || || || |_| |\__ \|   < | |_| |
|_||_||_| \__, ||___/|_|\_\ \__, |
          |___/             |___/

Driver for Vishay vcnl4010 v1.0.0
Copyright © 2024 illysky
*/   

#ifndef __vcnl4010_H
#define __vcnl4010_H

#ifdef __cplusplus
extern "C" {
#endif

#include <stdio.h>
#include <string.h>
#include <stdint.h>
#include <stdlib.h>
#include <zephyr/device.h>
#include <zephyr/devicetree.h>
#include <zephyr/kernel.h>

// VCNL4010_COMMAND_REGISTER
#define VCNL4010_COMMAND_REGISTER_ADDR 0x80
#define VCNL4010_COMMAND_REGISTER_SIZE 1
#define VCNL4010_COMMAND_REGISTER_SELFTIMED_EN_GET(v) FIELD_GET(GENMASK(0,0),v)
#define VCNL4010_COMMAND_REGISTER_SELFTIMED_EN_SET(i, v) (((i) & ~(GENMASK(0,0))) | FIELD_PREP((GENMASK(0,0)),(v)))
#define VCNL4010_COMMAND_REGISTER_PROX_EN_GET(v) FIELD_GET(GENMASK(1,1),v)
#define VCNL4010_COMMAND_REGISTER_PROX_EN_SET(i, v) (((i) & ~(GENMASK(1,1))) | FIELD_PREP((GENMASK(1,1)),(v)))
#define VCNL4010_COMMAND_REGISTER_ALS_EN_GET(v) FIELD_GET(GENMASK(2,2),v)
#define VCNL4010_COMMAND_REGISTER_ALS_EN_SET(i, v) (((i) & ~(GENMASK(2,2))) | FIELD_PREP((GENMASK(2,2)),(v)))
#define VCNL4010_COMMAND_REGISTER_PROX_OD_GET(v) FIELD_GET(GENMASK(3,3),v)
#define VCNL4010_COMMAND_REGISTER_PROX_OD_SET(i, v) (((i) & ~(GENMASK(3,3))) | FIELD_PREP((GENMASK(3,3)),(v)))
#define VCNL4010_COMMAND_REGISTER_ALS_OD_GET(v) FIELD_GET(GENMASK(4,4),v)
#define VCNL4010_COMMAND_REGISTER_ALS_OD_SET(i, v) (((i) & ~(GENMASK(4,4))) | FIELD_PREP((GENMASK(4,4)),(v)))
#define VCNL4010_COMMAND_REGISTER_PROX_DATA_RD_GET(v) FIELD_GET(GENMASK(5,5),v)
#define VCNL4010_COMMAND_REGISTER_PROX_DATA_RD_SET(i, v) (((i) & ~(GENMASK(5,5))) | FIELD_PREP((GENMASK(5,5)),(v)))
#define VCNL4010_COMMAND_REGISTER_ALS_DATA_RDY_GET(v) FIELD_GET(GENMASK(6,6),v)
#define VCNL4010_COMMAND_REGISTER_ALS_DATA_RDY_SET(i, v) (((i) & ~(GENMASK(6,6))) | FIELD_PREP((GENMASK(6,6)),(v)))
#define VCNL4010_COMMAND_REGISTER_CONFIG_LOCK_GET(v) FIELD_GET(GENMASK(7,7),v)
#define VCNL4010_COMMAND_REGISTER_CONFIG_LOCK_SET(i, v) (((i) & ~(GENMASK(7,7))) | FIELD_PREP((GENMASK(7,7)),(v)))

// VCNL4010_PRODUCT_ID_REVISION
#define VCNL4010_PRODUCT_ID_REVISION_ADDR 0x81
#define VCNL4010_PRODUCT_ID_REVISION_SIZE 1
#define VCNL4010_PRODUCT_ID_REVISION_REVISION_ID_GET(v) FIELD_GET(GENMASK(3,0),v)
#define VCNL4010_PRODUCT_ID_REVISION_REVISION_ID_SET(i, v) (((i) & ~(GENMASK(3,0))) | FIELD_PREP((GENMASK(3,0)),(v)))
#define VCNL4010_PRODUCT_ID_REVISION_PRODUCT_ID_GET(v) FIELD_GET(GENMASK(7,4),v)
#define VCNL4010_PRODUCT_ID_REVISION_PRODUCT_ID_SET(i, v) (((i) & ~(GENMASK(7,4))) | FIELD_PREP((GENMASK(7,4)),(v)))

// VCNL4010_RATE_OF_PROXIMITY_MEASUREMENT
#define VCNL4010_RATE_OF_PROXIMITY_MEASUREMENT_ADDR 0x82
#define VCNL4010_RATE_OF_PROXIMITY_MEASUREMENT_SIZE 1
#define VCNL4010_RATE_OF_PROXIMITY_MEASUREMENT_PROXIMITY_RATE_GET(v) FIELD_GET(GENMASK(2,0),v)
#define VCNL4010_RATE_OF_PROXIMITY_MEASUREMENT_PROXIMITY_RATE_SET(i, v) (((i) & ~(GENMASK(2,0))) | FIELD_PREP((GENMASK(2,0)),(v)))

// VCNL4010_LED_CURRENT_SETTING_PROXIMITY_MODE
#define VCNL4010_LED_CURRENT_SETTING_PROXIMITY_MODE_ADDR 0x83
#define VCNL4010_LED_CURRENT_SETTING_PROXIMITY_MODE_SIZE 1
#define VCNL4010_LED_CURRENT_SETTING_PROXIMITY_MODE_IR_LED_CURRENT_VALUE_GET(v) FIELD_GET(GENMASK(5,0),v)
#define VCNL4010_LED_CURRENT_SETTING_PROXIMITY_MODE_IR_LED_CURRENT_VALUE_SET(i, v) (((i) & ~(GENMASK(5,0))) | FIELD_PREP((GENMASK(5,0)),(v)))
#define VCNL4010_LED_CURRENT_SETTING_PROXIMITY_MODE_FUSE_PROG_ID_GET(v) FIELD_GET(GENMASK(7,6),v)
#define VCNL4010_LED_CURRENT_SETTING_PROXIMITY_MODE_FUSE_PROG_ID_SET(i, v) (((i) & ~(GENMASK(7,6))) | FIELD_PREP((GENMASK(7,6)),(v)))

// VCNL4010_AMBIENT_LIGHT_PARAMETER
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_ADDR 0x84
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_SIZE 1
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_AVERAGING_FUNCTION_GET(v) FIELD_GET(GENMASK(2,0),v)
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_AVERAGING_FUNCTION_SET(i, v) (((i) & ~(GENMASK(2,0))) | FIELD_PREP((GENMASK(2,0)),(v)))
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_AUTO_OFFSET_COMPENSATION_GET(v) FIELD_GET(GENMASK(3,3),v)
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_AUTO_OFFSET_COMPENSATION_SET(i, v) (((i) & ~(GENMASK(3,3))) | FIELD_PREP((GENMASK(3,3)),(v)))
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_AMBIENT_LIGHT_MEASUREMENT_RATE_GET(v) FIELD_GET(GENMASK(6,4),v)
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_AMBIENT_LIGHT_MEASUREMENT_RATE_SET(i, v) (((i) & ~(GENMASK(6,4))) | FIELD_PREP((GENMASK(6,4)),(v)))
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_CONT_CONVERSION_MODE_GET(v) FIELD_GET(GENMASK(7,7),v)
#define VCNL4010_AMBIENT_LIGHT_PARAMETER_CONT_CONVERSION_MODE_SET(i, v) (((i) & ~(GENMASK(7,7))) | FIELD_PREP((GENMASK(7,7)),(v)))

// VCNL4010_AMBIENT_LIGHT_RESULT_MSB
#define VCNL4010_AMBIENT_LIGHT_RESULT_MSB_ADDR 0x85
#define VCNL4010_AMBIENT_LIGHT_RESULT_MSB_SIZE 1
#define VCNL4010_AMBIENT_LIGHT_RESULT_MSB_MSB_GET(v) FIELD_GET(GENMASK(7,0),v)
#define VCNL4010_AMBIENT_LIGHT_RESULT_MSB_MSB_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// VCNL4010_AMBIENT_LIGHT_RESULT_LSB
#define VCNL4010_AMBIENT_LIGHT_RESULT_LSB_ADDR 0x86
#define VCNL4010_AMBIENT_LIGHT_RESULT_LSB_SIZE 1
#define VCNL4010_AMBIENT_LIGHT_RESULT_LSB_LSB_GET(v) FIELD_GET(GENMASK(7,0),v)
#define VCNL4010_AMBIENT_LIGHT_RESULT_LSB_LSB_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// VCNL4010_PROX_RESULT_MSB
#define VCNL4010_PROX_RESULT_MSB_ADDR 0x87
#define VCNL4010_PROX_RESULT_MSB_SIZE 1
#define VCNL4010_PROX_RESULT_MSB_MSB_GET(v) FIELD_GET(GENMASK(7,0),v)
#define VCNL4010_PROX_RESULT_MSB_MSB_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// VCNL4010_PROX_RESULT_LSB
#define VCNL4010_PROX_RESULT_LSB_ADDR 0x88
#define VCNL4010_PROX_RESULT_LSB_SIZE 1
#define VCNL4010_PROX_RESULT_LSB_LSB_GET(v) FIELD_GET(GENMASK(7,0),v)
#define VCNL4010_PROX_RESULT_LSB_LSB_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// VCNL4010_INTERRUPT_CONTROL_REGISTER
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_ADDR 0x89
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_SIZE 1
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_THRES_SEL_GET(v) FIELD_GET(GENMASK(0,0),v)
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_THRES_SEL_SET(i, v) (((i) & ~(GENMASK(0,0))) | FIELD_PREP((GENMASK(0,0)),(v)))
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_THRES_EN_GET(v) FIELD_GET(GENMASK(1,1),v)
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_THRES_EN_SET(i, v) (((i) & ~(GENMASK(1,1))) | FIELD_PREP((GENMASK(1,1)),(v)))
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_ALS_READY_EN_GET(v) FIELD_GET(GENMASK(2,2),v)
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_ALS_READY_EN_SET(i, v) (((i) & ~(GENMASK(2,2))) | FIELD_PREP((GENMASK(2,2)),(v)))
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_PROX_READY_EN_GET(v) FIELD_GET(GENMASK(3,3),v)
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_PROX_READY_EN_SET(i, v) (((i) & ~(GENMASK(3,3))) | FIELD_PREP((GENMASK(3,3)),(v)))
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_COUNT_EXCEED_GET(v) FIELD_GET(GENMASK(7,5),v)
#define VCNL4010_INTERRUPT_CONTROL_REGISTER_INT_COUNT_EXCEED_SET(i, v) (((i) & ~(GENMASK(7,5))) | FIELD_PREP((GENMASK(7,5)),(v)))

// VCNL4010_LOW_THRESHOLD_MSB
#define VCNL4010_LOW_THRESHOLD_MSB_ADDR 0x8A
#define VCNL4010_LOW_THRESHOLD_MSB_SIZE 1
#define VCNL4010_LOW_THRESHOLD_MSB_MSB_GET(v) FIELD_GET(GENMASK(7,0),v)
#define VCNL4010_LOW_THRESHOLD_MSB_MSB_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// VCNL4010_LOW_THRESHOLD_LSB
#define VCNL4010_LOW_THRESHOLD_LSB_ADDR 0x8B
#define VCNL4010_LOW_THRESHOLD_LSB_SIZE 1
#define VCNL4010_LOW_THRESHOLD_LSB_LSB_GET(v) FIELD_GET(GENMASK(7,0),v)
#define VCNL4010_LOW_THRESHOLD_LSB_LSB_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// VCNL4010_HIGH_THRESHOLD_MSB
#define VCNL4010_HIGH_THRESHOLD_MSB_ADDR 0x8C
#define VCNL4010_HIGH_THRESHOLD_MSB_SIZE 1
#define VCNL4010_HIGH_THRESHOLD_MSB_MSB_GET(v) FIELD_GET(GENMASK(7,0),v)
#define VCNL4010_HIGH_THRESHOLD_MSB_MSB_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// VCNL4010_HIGH_THRESHOLD_LSB
#define VCNL4010_HIGH_THRESHOLD_LSB_ADDR 0x8D
#define VCNL4010_HIGH_THRESHOLD_LSB_SIZE 1
#define VCNL4010_HIGH_THRESHOLD_LSB_LSB_GET(v) FIELD_GET(GENMASK(7,0),v)
#define VCNL4010_HIGH_THRESHOLD_LSB_LSB_SET(i, v) (((i) & ~(GENMASK(7,0))) | FIELD_PREP((GENMASK(7,0)),(v)))

// VCNL4010_INTERRUPT_STATUS
#define VCNL4010_INTERRUPT_STATUS_ADDR 0x8E
#define VCNL4010_INTERRUPT_STATUS_SIZE 1
#define VCNL4010_INTERRUPT_STATUS_INT_TH_HI_GET(v) FIELD_GET(GENMASK(0,0),v)
#define VCNL4010_INTERRUPT_STATUS_INT_TH_HI_SET(i, v) (((i) & ~(GENMASK(0,0))) | FIELD_PREP((GENMASK(0,0)),(v)))
#define VCNL4010_INTERRUPT_STATUS_INT_TH_LOW_GET(v) FIELD_GET(GENMASK(1,1),v)
#define VCNL4010_INTERRUPT_STATUS_INT_TH_LOW_SET(i, v) (((i) & ~(GENMASK(1,1))) | FIELD_PREP((GENMASK(1,1)),(v)))
#define VCNL4010_INTERRUPT_STATUS_INT_ALS_READY_GET(v) FIELD_GET(GENMASK(2,2),v)
#define VCNL4010_INTERRUPT_STATUS_INT_ALS_READY_SET(i, v) (((i) & ~(GENMASK(2,2))) | FIELD_PREP((GENMASK(2,2)),(v)))
#define VCNL4010_INTERRUPT_STATUS_INT_PROX_READY_GET(v) FIELD_GET(GENMASK(3,3),v)
#define VCNL4010_INTERRUPT_STATUS_INT_PROX_READY_SET(i, v) (((i) & ~(GENMASK(3,3))) | FIELD_PREP((GENMASK(3,3)),(v)))

// VCNL4010_PROXIMITY_MODULATOR_TIMING
#define VCNL4010_PROXIMITY_MODULATOR_TIMING_ADDR 0x8F
#define VCNL4010_PROXIMITY_MODULATOR_TIMING_SIZE 1
#define VCNL4010_PROXIMITY_MODULATOR_TIMING_MODULATION__DEAD_TIME_GET(v) FIELD_GET(GENMASK(2,0),v)
#define VCNL4010_PROXIMITY_MODULATOR_TIMING_MODULATION__DEAD_TIME_SET(i, v) (((i) & ~(GENMASK(2,0))) | FIELD_PREP((GENMASK(2,0)),(v)))
#define VCNL4010_PROXIMITY_MODULATOR_TIMING_IPROXIMITY_FREQUENCY_GET(v) FIELD_GET(GENMASK(4,3),v)
#define VCNL4010_PROXIMITY_MODULATOR_TIMING_IPROXIMITY_FREQUENCY_SET(i, v) (((i) & ~(GENMASK(4,3))) | FIELD_PREP((GENMASK(4,3)),(v)))
#define VCNL4010_PROXIMITY_MODULATOR_TIMING_MODULATION_DELAY_TIME_GET(v) FIELD_GET(GENMASK(7,5),v)
#define VCNL4010_PROXIMITY_MODULATOR_TIMING_MODULATION_DELAY_TIME_SET(i, v) (((i) & ~(GENMASK(7,5))) | FIELD_PREP((GENMASK(7,5)),(v)))



#ifdef __cplusplus
}
#endif
#endif // vcnl4010_H